#!/bin/bash

# File needs to be called /hooks/build relative to the Dockerfile.
# $IMAGE_NAME var is injected into the build so the tag is correct.
# See https://gist.github.com/rossf7/664dc1eb02f514993c7215d37058965c and
# https://docs.docker.com/docker-cloud/builds/advanced/

BUILD_ARCH=${DOCKER_TAG}
echo "Build hook running"
docker build \
             --file "${DOCKERFILE_PATH}"\
             --build-arg QEMU_ARCH=$([ "${BUILD_ARCH}" == "armhf" ] && echo "${BUILD_ARCH::-2}" || echo "${BUILD_ARCH}") \
             --build-arg IMAGE_ARCH=$([ "${BUILD_ARCH}" == "armhf" ] && echo "arm32v7/debian:stretch" || ([ "${BUILD_ARCH}" == "aarch64" ] && echo "arm64v8/debian:stretch") || echo "debian:stretch") \
             --build-arg ARCH=${DOCKER_TAG} \
             --tag "${IMAGE_NAME}" \
             .
